package com.futboldraft.modelo;
// Generated 13 feb 2025, 10:28:25 by Hibernate Tools 6.5.1.Final


/**
 * EventosPartido generated by hbm2java
 */
public class EventosPartido  implements java.io.Serializable {
	
	public enum tipoEventoEnum{GOL, PARADA, VAR, DESPEJE, OTRO};

     private Integer idEvento;
     private Jugador jugador;
     private Partido partido;
     private int minuto;
     private String tipoEvento;
     private String descripcion;

    public EventosPartido() {

    }

	
    public EventosPartido(Jugador jugador, Partido partido, int minuto, String tipoEvento) {
        this.jugador = jugador;
        this.partido = partido;
        this.minuto = minuto;
        this.tipoEvento = tipoEvento;
    }
    
    public EventosPartido(Jugador jugador, Partido partido, int minuto, String tipoEvento, String descripcion) {
       this.jugador = jugador;
       this.partido = partido;
       this.minuto = minuto;
       this.tipoEvento = tipoEvento;
       this.descripcion = descripcion;
    }
   
    public Integer getIdEvento() {
        return this.idEvento;
    }
    
    public void setIdEvento(Integer idEvento) {
        this.idEvento = idEvento;
    }
    public Jugador getJugador() {
        return this.jugador;
    }
    
    public void setJugador(Jugador jugador) {
        this.jugador = jugador;
    }
    public Partido getPartido() {
        return this.partido;
    }
    
    public void setPartido(Partido partido) {
        this.partido = partido;
    }
    public int getMinuto() {
        return this.minuto;
    }
    
    public void setMinuto(int minuto) {
        this.minuto = minuto;
    }
    public String getTipoEvento() {
        return this.tipoEvento;
    }
    
    public void setTipoEvento(String tipoEvento) {
        this.tipoEvento = tipoEvento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


