package com.futboldraft.modelo;
// Generated 13 feb 2025, 10:28:25 by Hibernate Tools 6.5.1.Final



/**
 * Goleador generated by hbm2java
 */
public class Goleador  implements java.io.Serializable {


     private int idJugador;
     private Jugador jugador;
     private Integer goles;

    public Goleador() {
    }

	
    public Goleador(Jugador jugador) {
        this.jugador = jugador;
    }
    public Goleador(Jugador jugador, Integer goles) {
       this.jugador = jugador;
       this.goles = goles;
    }
   
    public int getIdJugador() {
        return this.idJugador;
    }
    
    public void setIdJugador(int idJugador) {
        this.idJugador = idJugador;
    }
    public Jugador getJugador() {
        return this.jugador;
    }
    
    public void setJugador(Jugador jugador) {
        this.jugador = jugador;
    }
    public Integer getGoles() {
        return this.goles;
    }
    
    public void setGoles(Integer goles) {
        this.goles = goles;
    }




}


