package com.futboldraft.modelo;
// Generated 12 feb 2025, 16:34:06 by Hibernate Tools 6.5.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Jugador generated by hbm2java
 */
public class Jugador  implements java.io.Serializable {


     private Integer idJugador;
     private Equipo equipo;
     private String nombre;
     private String posicion;
     private int fuerzaAtaque;
     private int fuerzaDefensa;
     private int fuerzaPortero;
     private Goleador goleador;
     private Set eventosPartidos = new HashSet(0);

    public Jugador() {
    }

	
    public Jugador(String nombre, String posicion, int fuerzaAtaque, int fuerzaDefensa, int fuerzaPortero) {
        this.nombre = nombre;
        this.posicion = posicion;
        this.fuerzaAtaque = fuerzaAtaque;
        this.fuerzaDefensa = fuerzaDefensa;
        this.fuerzaPortero = fuerzaPortero;
    }
    public Jugador(Equipo equipo, String nombre, String posicion, int fuerzaAtaque, int fuerzaDefensa, int fuerzaPortero, Goleador goleador, Set eventosPartidos) {
       this.equipo = equipo;
       this.nombre = nombre;
       this.posicion = posicion;
       this.fuerzaAtaque = fuerzaAtaque;
       this.fuerzaDefensa = fuerzaDefensa;
       this.fuerzaPortero = fuerzaPortero;
       this.goleador = goleador;
       this.eventosPartidos = eventosPartidos;
    }
   
    public Integer getIdJugador() {
        return this.idJugador;
    }
    
    public void setIdJugador(Integer idJugador) {
        this.idJugador = idJugador;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPosicion() {
        return this.posicion;
    }
    
    public void setPosicion(String posicion) {
        this.posicion = posicion;
    }
    public int getFuerzaAtaque() {
        return this.fuerzaAtaque;
    }
    
    public void setFuerzaAtaque(int fuerzaAtaque) {
        this.fuerzaAtaque = fuerzaAtaque;
    }
    public int getFuerzaDefensa() {
        return this.fuerzaDefensa;
    }
    
    public void setFuerzaDefensa(int fuerzaDefensa) {
        this.fuerzaDefensa = fuerzaDefensa;
    }
    public int getFuerzaPortero() {
        return this.fuerzaPortero;
    }
    
    public void setFuerzaPortero(int fuerzaPortero) {
        this.fuerzaPortero = fuerzaPortero;
    }
    public Goleador getGoleador() {
        return this.goleador;
    }
    
    public void setGoleador(Goleador goleador) {
        this.goleador = goleador;
    }
    public Set getEventosPartidos() {
        return this.eventosPartidos;
    }
    
    public void setEventosPartidos(Set eventosPartidos) {
        this.eventosPartidos = eventosPartidos;
    }




}


