package com.futboldraft.modelo;
// Generated 12 feb 2025, 18:13:57 by Hibernate Tools 6.5.1.Final


import java.io.FileReader;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.opencsv.bean.CsvBindByName;
import com.opencsv.bean.CsvToBean;
import com.opencsv.bean.CsvToBeanBuilder;

/**
 * Jugador generated by hbm2java
 */
public class Jugador  implements java.io.Serializable {


     private Integer idJugador;
     @CsvBindByName(column = "Equipo")
     private Equipo equipo;
     @CsvBindByName(column = "Nombre")
     private String nombre;
     @CsvBindByName(column = "Posicion")
     private String posicion;
     @CsvBindByName(column = "FuerzaAtaque")
     private int fuerzaAtaque;
     @CsvBindByName(column = "FuerzaTecnica")
     private int fuerzaTecnica;
     @CsvBindByName(column = "FuerzaDefensa")
     private int fuerzaDefensa;
     @CsvBindByName(column = "FuerzaPortero")
     private int fuerzaPortero;
     private Goleador goleador;
     private Set eventosPartidos = new HashSet(0);
     
     public List<Jugador> abrirCSV() {
 		List<Jugador> jugadores = null;
 		try {
 			FileReader reader = new FileReader("main/resources/jugadores_ligaFantasy.csv");

 			CsvToBeanBuilder<Jugador> csvBuilder = new CsvToBeanBuilder<>(reader);
 			CsvToBean<Jugador> csv = csvBuilder.withType(Jugador.class).withIgnoreLeadingWhiteSpace(true).build();

 			jugadores = csv.parse();

 		} catch (Exception e) {
 			e.printStackTrace();
 		}

 		return jugadores;
 	}

    public Jugador() {
    }

	
    public Jugador(String nombre, String posicion, int fuerzaAtaque, int fuerzaTecnica, int fuerzaDefensa, int fuerzaPortero) {
        this.nombre = nombre;
        this.posicion = posicion;
        this.fuerzaAtaque = fuerzaAtaque;
        this.fuerzaTecnica = fuerzaTecnica;
        this.fuerzaDefensa = fuerzaDefensa;
        this.fuerzaPortero = fuerzaPortero;
    }
    public Jugador(Equipo equipo, String nombre, String posicion, int fuerzaAtaque, int fuerzaTecnica, int fuerzaDefensa, int fuerzaPortero, Goleador goleador, Set eventosPartidos) {
       this.equipo = equipo;
       this.nombre = nombre;
       this.posicion = posicion;
       this.fuerzaAtaque = fuerzaAtaque;
       this.fuerzaTecnica = fuerzaTecnica;
       this.fuerzaDefensa = fuerzaDefensa;
       this.fuerzaPortero = fuerzaPortero;
       this.goleador = goleador;
       this.eventosPartidos = eventosPartidos;
    }
   
    public Integer getIdJugador() {
        return this.idJugador;
    }
    
    public void setIdJugador(Integer idJugador) {
        this.idJugador = idJugador;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPosicion() {
        return this.posicion;
    }
    
    public void setPosicion(String posicion) {
        this.posicion = posicion;
    }
    public int getFuerzaAtaque() {
        return this.fuerzaAtaque;
    }
    
    public void setFuerzaAtaque(int fuerzaAtaque) {
        this.fuerzaAtaque = fuerzaAtaque;
    }
    public int getFuerzaTecnica() {
        return this.fuerzaTecnica;
    }
    
    public void setFuerzaTecnica(int fuerzaTecnica) {
        this.fuerzaTecnica = fuerzaTecnica;
    }
    public int getFuerzaDefensa() {
        return this.fuerzaDefensa;
    }
    
    public void setFuerzaDefensa(int fuerzaDefensa) {
        this.fuerzaDefensa = fuerzaDefensa;
    }
    public int getFuerzaPortero() {
        return this.fuerzaPortero;
    }
    
    public void setFuerzaPortero(int fuerzaPortero) {
        this.fuerzaPortero = fuerzaPortero;
    }
    public Goleador getGoleador() {
        return this.goleador;
    }
    
    public void setGoleador(Goleador goleador) {
        this.goleador = goleador;
    }
    public Set getEventosPartidos() {
        return this.eventosPartidos;
    }
    
    public void setEventosPartidos(Set eventosPartidos) {
        this.eventosPartidos = eventosPartidos;
    }




}


